### ISSUE TITLE
Video Save

### ISSUE THREAD

**Issue by stephenbrew** [lmylr/HardwareVideoCodec#1]
I am not able to save the video can you please tell me how and where I can save the video recorded with effect?

**Comment by lmylr** [comment]
How did you use it?Can I see your code?

**Comment by stephenbrew** [comment]
Thank you for your reply I got the code to save the recorded video but my other question is can we use it for videos saved in gallery can we apply effect on recorded video and save it again with effects applied

**Comment by lmylr** [comment]
@stephenbrew This is not supported now. But I plan to support this feature in a future release. This may take a while, please stay tuned for our updates. Thank you for your issue.
